#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gts7xlwifi

PRODUCT_COPY_FILES += \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/audconf/OPEN/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Bluetooth_cal.acdb \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/audconf/OPEN/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Codec_cal.acdb \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/audconf/OPEN/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/General_cal.acdb \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/audconf/OPEN/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Global_cal.acdb \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/audconf/OPEN/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Handset_cal.acdb \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/audconf/OPEN/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Hdmi_cal.acdb \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/audconf/OPEN/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Headset_cal.acdb \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/audconf/OPEN/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Speaker_cal.acdb \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/audconf/OPEN/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/workspaceFile.qwsp \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/btcon.json:$(TARGET_COPY_OUT_VENDOR)/etc/btcon.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/gnss/deleteLogCommands:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/deleteLogCommands \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/gnss/gps.cer:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.cer \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/gnss/gps.debug.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.debug.xml \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/gnss/gps.gsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.gsi.xml \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/gnss/gps.issuetracker.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.issuetracker.xml \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/gnss/gps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.xml \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/init/init.gps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rc \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss@2.0-service.rc \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/qdcm_calib_data_ss_dsi_panel_S6TUUM2_AMSA24VU01_WQXGA.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ss_dsi_panel_S6TUUM2_AMSA24VU01_WQXGA.xml \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/qdcm_calib_data_ss_dsi_panel_S6TUUM3_AMSA24VU01_WQXGA.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ss_dsi_panel_S6TUUM3_AMSA24VU01_WQXGA.xml \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/ak991x_polling_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_polling_0.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/bridge_driver_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bridge_driver_0.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/kona_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_ak991x_0.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/kona_ak991x_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_ak991x_2.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/kona_ak991x_6.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_ak991x_6.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/kona_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_default_sensors.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/kona_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_irq.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/kona_lsm6dso_0_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_lsm6dso_0_0.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/kona_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_power_0.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/kona_qrd_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_qrd_lsm6dso_0.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/kona_veml3328_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_veml3328_0.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/kona_veml3328_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kona_veml3328_1.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/lsm6dso_0_8g.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0_8g.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/pah_8011_0_platform.ppg_enable_ex_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pah_8011_0_platform.ppg_enable_ex_1.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/pah_8011_0_platform.ppg_enable_ex_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pah_8011_0_platform.ppg_enable_ex_2.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_hw_revision.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_hw_revision.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/veml3328_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/veml3328_0.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/config/veml3328_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/veml3328_1.json \
    vendor/samsung/gts7xlwifi/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/samsung/gts7xlwifi/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/samsung/gts7xlwifi/proprietary/vendor/firmware/cs35l40-spk-dsp1-spk-prot-calib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l40-spk-dsp1-spk-prot-calib.bin \
    vendor/samsung/gts7xlwifi/proprietary/vendor/firmware/cs35l40-spk-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l40-spk-dsp1-spk-prot.bin \
    vendor/samsung/gts7xlwifi/proprietary/vendor/firmware/cs35l40-spk-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l40-spk-dsp1-spk-prot.wmfw \
    vendor/samsung/gts7xlwifi/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_lsi_s5k3m5.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_lsi_s5k3m5.bin \
    vendor/samsung/gts7xlwifi/proprietary/vendor/lib64/camera/com.samsung.sensormodule.12_lsi_s5k4ha_full.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.12_lsi_s5k4ha_full.bin \
    vendor/samsung/gts7xlwifi/proprietary/vendor/lib64/camera/com.samsung.sensormodule.1_lsi_s5k4ha.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.1_lsi_s5k4ha.bin \
    vendor/samsung/gts7xlwifi/proprietary/vendor/lib64/camera/com.samsung.sensormodule.2_lsi_s5k5e9yu05.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.2_lsi_s5k5e9yu05.bin \
    vendor/samsung/gts7xlwifi/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5k3m5.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5k3m5.bin \
    vendor/samsung/gts7xlwifi/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5k4ha.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5k4ha.bin \
    vendor/samsung/gts7xlwifi/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5k5e9yu05.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5k5e9yu05.bin

PRODUCT_PACKAGES += \
    A08QL_libTsAeFront \
    A08QL_libTsAfFront \
    A08QL_libTsAwbFront \
    A08QL_libTsPdafm_Front \
    B13QL_libTsAe \
    B13QL_libTsAf \
    B13QL_libTsAwb \
    B13QL_libTsPdafm \
    com.samsung.sensor.s5k3m5 \
    com.samsung.sensor.s5k4ha \
    com.samsung.sensor.s5k5e9yu05 \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.depth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.remosaic \
    com.qti.node.sbi \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.tracker \
    com.samsung.node.capture_bokeh \
    com.samsung.node.multi_frame_video_hdr \
    com.samsung.node.realtimebokeh \
    com.samsung.node.smooth_transition \
    com.ss.stats.aec \
    com.ss.stats.af \
    com.ss.stats.awb \
    com.ss.stats.pdlib \
    libdepthmapwrapper \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs \
    com.qti.feature2.hdr \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.rt \
    com.qti.feature2.serializer \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    android.hardware.gnss@2.0-impl \
    com.qti.chi.override \
    flp.default \
    gps.default \
    vendor.samsung.hardware.gnss@2.0-impl \
    libbauthserver \
    libbauthtzcommon \
    libdualcam_optical_zoom_control \
    libdualcam_refocus_video \
    libdualcam_video_optical_zoom \
    libegis_fp_normal_sensor_test \
    libgf_in_system_lib \
    libqfp_sensortest \
    libsynaFpSensorTestNwd \
    libthirdparty_zoomtranslator_imp \
    libvdis_interface \
    libwrappergps \
    sensors.grip \
    sensors.ssc \
    vendor.samsung.hardware.gnss@2.0 \
    gps \
    gpsd \
    vendor.samsung.hardware.gnss@2.0-service
